### ISSUE TITLE
ERROR: torchvision 0.4.0 has requirement torch==1.2.0, but you'll have torch 1.3.0 which is incompatible.

### ISSUE THREAD

**Issue by rassaire** [gaocong13/Projective-Spatial-Transformers#1]
Hi, @gaocong13  I am getting this error message when installing the requirement file.
ERROR: torchvision 0.4.0 has requirement torch==1.2.0, but you'll have torch 1.3.0 which is incompatible.
when I  ignored that and ran the setup.py file, I got the this error message
ProSTGrid.cpp:92:79: error: ‘torch::IntArrayRef’ has not been declared
 torch::Tensor ProST_grid_generator_forward(const torch::Tensor &theta, torch::IntArrayRef size, float dist_min, float dist_max, float src, float det, float pix_spacing, float step_size, bool align_corners) {
                                                                               ^~~~~~~~~~~
ProSTGrid.cpp: In function ‘at::Tensor ProST_grid_generator_forward(const at::Tensor&, int, float, float, float, float, float, float, bool)’:
ProSTGrid.cpp:95:62: error: invalid types ‘int[int]’ for array subscript
     return ProST_grid_generator_5D_cuda_forward(theta, size[0], size[1], size[2], size[3], dist_min, dist_max, src, det, pix_spacing, step_size, align_corners);
                                                              ^
ProSTGrid.cpp:95:71: error: invalid types ‘int[int]’ for array subscript
     return ProST_grid_generator_5D_cuda_forward(theta, size[0], size[1], size[2], size[3], dist_min, dist_max, src, det, pix_spacing, step_size, align_corners);
                                                                       ^
ProSTGrid.cpp:95:80: error: invalid types ‘int[int]’ for array subscript
     return ProST_grid_generator_5D_cuda_forward(theta, size[0], size[1], size[2], size[3], dist_min, dist_max, src, det, pix_spacing, step_size, align_corners);
                                                                                ^
ProSTGrid.cpp:95:89: error: invalid types ‘int[int]’ for array subscript
     return ProST_grid_generator_5D_cuda_forward(theta, size[0], size[1], size[2], size[3], dist_min, dist_max, src, det, pix_spacing, step_size, align_corners);
                                                                                         ^
ProSTGrid.cpp:97:61: error: invalid types ‘int[int]’ for array subscript
     return ProST_grid_generator_5D_cpu_forward(theta, size[0], size[1], size[2], size[3], dist_min, dist_max, src, det, pix_spacing, step_size, align_corners);
                                                             ^
ProSTGrid.cpp:97:70: error: invalid types ‘int[int]’ for array subscript
     return ProST_grid_generator_5D_cpu_forward(theta, size[0], size[1], size[2], size[3], dist_min, dist_max, src, det, pix_spacing, step_size, align_corners);
                                                                      ^
ProSTGrid.cpp:97:79: error: invalid types ‘int[int]’ for array subscript
     return ProST_grid_generator_5D_cpu_forward(theta, size[0], size[1], size[2], size[3], dist_min, dist_max, src, det, pix_spacing, step_size, align_corners);
                                                                               ^
ProSTGrid.cpp:97:88: error: invalid types ‘int[int]’ for array subscript
     return ProST_grid_generator_5D_cpu_forward(theta, size[0], size[1], size[2], size[3], dist_min, dist_max, src, det, pix_spacing, step_size, align_corners);
                                                                                        ^
error: command 'gcc' failed with exit status 1

can you help?

**Comment by gaocong13** [comment]
Could you check your gcc version? Might be gcc is not up-to-date.

**Comment by rassaire** [comment]
Thanks @gaocong13 I'll it check out.

**Comment by rassaire** [comment]
sorted that out. I think it had something to do with my local env.  it wasn't the gcc version because I was using gcc 8+
