### ISSUE TITLE
6D pose 

### ISSUE THREAD

**Issue by xsk0802** [gaocong13/Projective-Spatial-Transformers#11]
Hello, I want to know whether the pose parameter in the code is the pose of the emitter or the pose of the volume data?

**Comment by gaocong13** [comment]
Hi, the pose parameter is the rigid transformation of the projective grid points relative to the canonical position. Please refer to Fig.1 in the paper for illustration. 

Since the pose of grid points and volume is relative. Pose of the volume can be derived as its inverse.
