### ISSUE TITLE
AttributeError: module 'ProSTGrid' has no attribute 'forward'

### ISSUE THREAD

**Issue by rassaire** [gaocong13/Projective-Spatial-Transformers#13]
Hi,
 I am trying to use ProSTGrid' in a code. I have successfully installed it, but when I call it in code I get this error.

    grid = ProSTGrid.forward(corner_pt, y.size(), dist_min.data, dist_max.data,\
AttributeError: module 'ProSTGrid' has no attribute 'forward'

Can you help please?

**Comment by rassaire** [comment]
I get the same error when I try to the ProST_example_regi.py file.

**Comment by gaocong13** [comment]
Hi, to follow up with the debugging, could you do the following and print the output
`>>> import torch`
`>>> import ProSTGrid`
`>>> print(ProSTGrid.forward)`
If it is imported correctly, I am hoping you can see something like:
`<built-in method forward of PyCapsule object at 0x7f87cb84a660>`

**Comment by rassaire** [comment]
Hi @gaocong13 , thanks. In fact, it works now. The problem was linked with Pycharm. I was using the Pytcharm code execution button to execute the file. When instead I used the terminal, it worked.

**Comment by TUYaYa1** [comment]
Hello, do you have successfully run the code? When I ran train.py, the following error occurred: "AttributeError: module 'geomstats.geometry.riemannian_metric' has no attribute 'loss'". But Package "geomstats" has been successfully installed. Can you help me solve this problem?

**Comment by rassaire** [comment]
Hi, I got the error I posted because I was running my code using an IDE. while it worked when I ran it from the command line.  For you, I don't know if you are using an IDE. If you are, try to run it from the command line.

**Comment by TUYaYa1** [comment]
Thank you, I can run the code successfully now.
