### ISSUE TITLE
Doubts about the function conv_hu_to_density

### ISSUE THREAD

**Issue by wangyunpengbio** [gaocong13/Projective-Spatial-Transformers#15]
This idea about Projective Spatial Transformer is awesome. Thank @gaocong13 a lot for sharing your work.
I am confused about the hard-coded parameters in the source code.
For `mu_water_` and `mu_air_`, you set it to be `0.02683*1.0` and `0.02485*0.0001`. Are these values for the density of water and air? Then `hu_scale_ = (mu_water_ - mu_air_) * 0.001`. Does multiplying by `0.001` have any special meaning?
I have searched the information, and the HU value of air is -1000, the density is 1.29Kg/m³, the HU value of water is 0, and the density is 997 kg/m³. I can't find its relation to hard-coded parameters in your code. Since this is not a common normalization method based on window width and window level, I am curious about the meaning of these parameters. 
If you could take a little time to explain this function, I would be very grateful.
```
# Convert CT HU value to attenuation line integral
def conv_hu_to_density(vol):
    vol = vol.astype(float)
    mu_water_ = 0.02683*1.0
    mu_air_   = 0.02485*0.0001
    hu_lower_ = -130
    hu_scale_ = (mu_water_ - mu_air_) * 0.001
    mu_lower_ = (hu_lower_ * hu_scale_) + mu_water_
    densities = np.maximum((vol*hu_scale_) + mu_water_ - mu_lower_, 0)
    return densities
```

**Comment by gaocong13** [comment]
Hi @wangyunpengbio, thanks for your interest in our work! 

mu_water_ and mu_air_ refer to attenuation coefficients of water and air. The hu_scale_ and the formula in this code are generally derived from the definition of HU. There are multiple resources online but if you look into [this reference](https://www.sciencedirect.com/topics/medicine-and-dentistry/hounsfield-scale), equation (9.1), this scale can be derived if you want to express mu. There is a thresholding cut off (np.maximum(...)) to make sure the densities are converted reasonably.

I feel the confusion may come from the variable densities, which should be attenuation. 

This piece of code, especially the hard coded parameters, is derived from our another registration software, [xreg.](https://github.com/rg2/xreg)  You are welcome to check out [this file](https://github.com/rg2/xreg/blob/deb282911b01edd178b18c60abc6391e93ad35e8/lib/image/xregHUToLinAtt.cpp#L63).

I hope these help!

**Comment by wangyunpengbio** [comment]
Thank you very much for your response. That helps a lot. I didn't expect that [xreg](https://github.com/rg2/xreg) is also the work of your group. I was also impressed by that software before.
With your help, I checked some more information and found that the attenuation coefficients of air and water are **indeed well-founded**. 
|Energy|μ/ρ|μen/ρ|Material|
| ------------- | ------------- |------------- |------------- |
|(MeV)|(cm2/g)|(cm2/g)||
|4.00E-02|**2.683E-01**|6.947E-02|water|
|4.00E-02|**2.485E-01**|6.83E-02|air|

**μ/ρ are the values of the mass attenuation coefficient** and μen/ρ are the mass energy-absorption coefficient, 

However, if multiplying μ/ρ by the density (ρ) to get μ, then it's a bit different from the μ for water and air in your code.
The μ/ρ of water and air are of the same magnitude. The density ratio of air and water is 0.001. Therefore, the μ ratio of water and air should be 0.001 instead of 0.0001.
So, the code `mu_air_   = 0.02485*0.0001` may change to `mu_air_   = 0.02485*0.001`?

I would like to know whether my understanding is correct, thank you very much for your help.

Table data from: 
- https://physics.nist.gov/PhysRefData/XrayMassCoef/ComTab/air.html
- https://physics.nist.gov/PhysRefData/XrayMassCoef/ComTab/water.html

**Comment by gaocong13** [comment]
Hi, I apologize for the delayed response and thanks for your catch! You are correct. I have updated `mu_air_` in the recent commit. I will close this issue.

Thanks again for your detailed check and comments.
