### ISSUE TITLE
Getting RuntimeError about ProST_example_regi.py

### ISSUE THREAD

**Issue by victorswan** [gaocong13/Projective-Spatial-Transformers#16]
when I try to run the ProST_example_regi.py for testing. I get RuntimeError like this:

(pytorch) C:\Users\Administrator\Desktop\Projective-Spatial-Transformers-master\src>python ProST_example_regi.py
C:\Users\Administrator\Desktop\Projective-Spatial-Transformers-master\src\util.py:152: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  rtvec = torch.tensor(rtvec.detach(), requires_grad=True, device=device)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Projective-Spatial-Transformers-master\src\ProST_example_regi.py", line 78, in <module>
    main()
  File "C:\Users\Administrator\Desktop\Projective-Spatial-Transformers-master\src\ProST_example_regi.py", line 59, in main
    proj_mov = projmodel(_3D_vol, target, rtvec, corner_pt)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Administrator\Desktop\Projective-Spatial-Transformers-master\src\module.py", line 170, in forward
    grid = ProSTGrid.forward(corner_pt, y.size(), dist_min.data, dist_max.data,\
RuntimeError: unsupported range: nan -> nan
(pytorch) C:\Users\Administrator\Desktop\Projective-Spatial-Transformers-master\src>

how to work it around

**Comment by gaocong13** [comment]
Hi @victorswan, this looks like your 3D CT volume is positioned outside of the projection view. The projection is essentially an empty image, which triggers this nan issue. 

What is the CT data you are using? I recommend you double-check your [input CT data and processing](https://github.com/gaocong13/Projective-Spatial-Transformers/blob/f89a557009cb4e52dcda6b2c93932f2e2ee4b2d2/src/util.py#L65). By default, the center of CT volume is positioned at the origin of the projection geometry.

Let me know if you have found any clues.

**Comment by victorswan** [comment]
thanks so much for your kindly reply. actually I didn't test with my own data. I just check out your repository of [Projective-Spatial-Transformers](https://github.com/gaocong13/Projective-Spatial-Transformers). running follow your readme while getting this RuntimeError.

**Comment by victorswan** [comment]
my enviroment is: python 3.9.12 with cuda version11.3 and torch version 1.12.0

**Comment by rashmi05pathak** [comment]
I am getting below warning and no output is coming while running python ProST_example_regi.py:

Projective-Spatial-Transformers-master/src/util.py:152:
serWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  rtvec = torch.tensor(rtvec.detach(), requires_grad=True, device=device)

@gaocong13 could you please look into it?

**Comment by gaocong13** [comment]
Hi @rashmi05pathak , the warning should be fine. Are you also getting the nan output error?

**Comment by victorswan** [comment]
@gaocong13 it is me.  cuda version11.3 and torch version 1.12.0. getting output nan error

**Comment by rashmi05pathak** [comment]
> Hi @rashmi05pathak , the warning should be fine. Are you also getting the nan output error?

@gaocong13 Thanks for replying. Now I am able to get the proper output. Just I needed to include Jupiter Notebook in Visual Studio Code, which I was missing earlier. Have followed: https://stackoverflow.com/questions/49992300/python-how-to-show-graph-in-visual-studio-code-itself

ProST_example_regy.py is working absolutely fine.

**Comment by victorswan** [comment]
I am confused. getting the nan ouput error is on Windows 10 platform. when I switched to Ubuntu 20.04. the same environment: python 3.9.13, pytorch 1.12.1 and  cuda 11.3. the program ProST_example_regi.py can get good result. everything is ok except 1-x should be changed to ~x in torchgeometry/core/conversions.py

**Comment by gaocong13** [comment]
Glad to hear that you figured it out! @rashmi05pathak 

@victorswan Yes, I had similar issue when I was testing in windows environment. I bet it's related to Pytorch support of C++ and CUDA extension on Windows. I would highly recommend running on Linux to avoid more issues.

**Comment by victorswan** [comment]
OK. thanks so much.^_^

**Comment by victorswan** [comment]
@gaocong13 I wrote a mail to you(cgao11@jhu.edu) two weeks ago. If you have received then would you like to anser me. thanks so much in advavce

**Comment by gaocong13** [comment]
Hello @victorswan , I apologize that I lost track of your email. What is your issue?
