### ISSUE TITLE
Run on windows10 enviroment

### ISSUE THREAD

**Issue by TUYaYa1** [gaocong13/Projective-Spatial-Transformers#17]
Hello, I installed CPU versions of ProSTGrid_cpuonly in the Windows 10 environment and prompted the following error. Can you help me solve it?
PS C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master> cd ./ProSTGrid_cpuonly
PS C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\ProSTGrid_cpuonly> python setup_cpuonly.py install
running install
running bdist_egg
running egg_info
writing manifest file 'ProSTGrid_cpu.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2]  系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'ProSTGrid_cpu' extension
Emitting ninja build file C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\ProSTGrid_cpuonly\build\temp.win-amd64-3.9\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\
venv\lib\site-packages\torch\include -IC:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\yyy\Desktop\Pr
ojective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\TH -IC:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\THC -IC:
\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\include -IC:\Users\yyy\AppData\Local\Programs\Python\Python39\include -IC:\Users\yyy\AppData\Local\Programs\Python\Python
39\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kit
s\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c C:\Users\yyy\Desktop\Projective-Spatial-Transf
ormers-master\ProSTGrid_cpuonly\ProSTGrid_cpu.cpp /FoC:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\ProSTGrid_cpuonly\build\temp.win-amd64-3.9\Release\ProSTGrid_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ProSTGrid_cpu -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/yyy/Desktop/Projective-Spatial-Transformers-master/ProSTGrid_cpuonly/build/temp.win-amd64-3.9/Release/ProSTGrid_cpu.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\l
ib\site-packages\torch\include -IC:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\yyy\Desktop\Projecti
ve-Spatial-Transformers-master\venv\lib\site-packages\torch\include\TH -IC:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\THC -IC:\Users
\yyy\Desktop\Projective-Spatial-Transformers-master\venv\include -IC:\Users\yyy\AppData\Local\Programs\Python\Python39\include -IC:\Users\yyy\AppData\Local\Programs\Python\Python39\inc
lude "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\
include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c C:\Users\yyy\Desktop\Projective-Spatial-Transformers
-master\ProSTGrid_cpuonly\ProSTGrid_cpu.cpp /FoC:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\ProSTGrid_cpuonly\build\temp.win-amd64-3.9\Release\ProSTGrid_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ProSTGrid_cpu -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/macros/Macros.h(143): warning C4067: unexpected tokens following preprocessor directive - expected a newline
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/reverse_iterator.h(92): warning C4814: 'c10::reverse_iterator<_Iterator>::operator =': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/reverse_iterator.h(176): note: see reference to class template instantiation 'c10::reverse_iterator<_Iterator>' being compiled
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/reverse_iterator.h(125): warning C4814: 'c10::reverse_iterator<_Iterator>::operator ++': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/reverse_iterator.h(131): warning C4814: 'c10::reverse_iterator<_Iterator>::operator ++': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/reverse_iterator.h(136): warning C4814: 'c10::reverse_iterator<_Iterator>::operator --': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/reverse_iterator.h(142): warning C4814: 'c10::reverse_iterator<_Iterator>::operator --': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/reverse_iterator.h(151): warning C4814: 'c10::reverse_iterator<_Iterator>::operator +=': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/reverse_iterator.h(160): warning C4814: 'c10::reverse_iterator<_Iterator>::operator -=': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/string_view.h(64): warning C4814: 'c10::basic_string_view<CharT>::operator =': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/string_view.h(648): note: see reference to class template instantiation 'c10::basic_string_view<CharT>' being compiled
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/string_view.h(166): warning C4814: 'c10::basic_string_view<CharT>::remove_prefix': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/string_view.h(175): warning C4814: 'c10::basic_string_view<CharT>::remove_suffix': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/string_view.h(181): warning C4814: 'c10::basic_string_view<CharT>::swap': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/string_view.h(64): warning C4814: 'c10::basic_string_view<char>::operator =': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/StringUtil.h(143): note: see reference to class template instantiation 'c10::basic_string_view<char>' being compiled
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/string_view.h(166): warning C4814: 'c10::basic_string_view<char>::remove_prefix': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/string_view.h(175): warning C4814: 'c10::basic_string_view<char>::remove_suffix': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/util/string_view.h(181): warning C4814: 'c10::basic_string_view<char>::swap': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(599): error C3249: illegal statement or sub-expression for 'constexpr' function
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(598): error C3249: illegal statement or sub-expression for 'constexpr' function
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(600): error C3249: illegal statement or sub-expression for 'constexpr' function
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(597): error C3259: 'constexpr' functions can only have one return statement
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(626): error C3250: 'count': declaration is not allowed in 'constexpr' function body
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(626): error C3249: illegal statement or sub-expression for 'constexpr' function
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(627): error C3250: 'k': declaration is not allowed in 'constexpr' function body
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(627): error C3249: illegal statement or sub-expression for 'constexpr' function
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(627): note: see usage of '++'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(628): error C3249: illegal statement or sub-expression for 'constexpr' function
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(629): error C3249: illegal statement or sub-expression for 'constexpr' function
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(629): note: see usage of '++'
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(631): error C3256: 'count': variable use does not produce a constant expression
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(639): error C2131: expression did not evaluate to a constant    
C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\include\c10/core/DispatchKey.h(631): note: a non-constant (sub-)expression was encountered     
Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\ProSTGrid_cpuonly\setup_cpuonly.py", line 4, in <module>
    setup(
  File "C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    _write_ninja_file_and_compile_objects(
  File "C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\yyy\Desktop\Projective-Spatial-Transformers-master\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by gaocong13** [comment]
Hi, I have met a similar compiling issue of ProST running on a Windows environment. This is due to Pytorch cpp extension support in Windows. I strongly recommend running this software using a Linux machine. I have not successfully run in Windows myself.

**Comment by TUYaYa1** [comment]
Thanks，I tried to use the Linux machine and it ran successfully.
