### ISSUE TITLE
undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by rassaire** [gaocong13/Projective-Spatial-Transformers#2]
Hi, @gaocong13  I installed  ProSTGrid, he is the message showing that it was installed.
"Installed /home/ffcjea001/python-PST/lib/python3.7/site-packages/ProSTGrid-0.0.0-py3.7-linux-x86_64.egg
Processing dependencies for ProSTGrid==0.0.0
Finished processing dependencies for ProSTGrid==0.0.0
"

but when I import ProSTGrid, I get this error message 
ImportError: /home/ffcjea001/python-PST/lib/python3.7/site-packages/ProSTGrid-0.0.0-py3.7-linux-x86_64.egg/ProSTGrid.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

please can you help?

**Comment by gaocong13** [comment]
You need to make sure to “import torch” first before “import ProST”.

**Comment by rassaire** [comment]
yes that works, thanks @gaocong13
