### ISSUE TITLE
ProSTGrid_cpu Expected 3-dimensional tensor, but got 5-dimensional tensor

### ISSUE THREAD

**Issue by soanduong** [gaocong13/Projective-Spatial-Transformers#6]
Thanks, Gao for such an excellent idea and work on the projective spatial transformers.

I have tried to implement your method on Window with CPU. So I replace `ProSTGrid ` by `ProSTGrid_cpu ` in file `src\module.py`.

However, whenever I run the command
`target = initmodel(CT_vol, ray_proj_mov, transform_mat3x4_gt, corner_pt)`
and I got the below error:
```
grid_trans = grid.bmm(transform_mat3x4.transpose(1,2)).view(BATCH_SIZE, H, W, -1, 3)
RuntimeError: Expected 3-dimensional tensor, but got 5-dimensional tensor for argument #1 'batch1' (while checking arguments for bmm)
```
The sizes of the inputs params for the function `initmodel` are:
- `CT_vol`: `torch.Size([2, 1, 128, 128, 128])`
- r`ay_proj_mov`: `torch.Size([2, 1, 128, 128])`
- `transform_mat3x4_gt`: `torch.Size([2, 3, 4])`
- `corner_pt`: `torch.Size([2, 8, 3])`

And the size of the variable `grid `after line 191 in `src\module.py` is: `torch.Size([2, 128, 128, 182, 4]`).

I am having trouble figuring out where this issue is coming from and was wondering if you would have any ideas on what might go wrong or how to address it? Any help you have to offer would be greatly appreciated.

Best,
Soan

**Comment by gaocong13** [comment]
Hi, sorry for the delayed response and thank you for your interest!

This is a bug of inconsistency between CUDA and CPU versions. I have updated the CPU version .cpp file. Would you mind try it again and let me know whether it works for you?

**Comment by soanduong** [comment]
@gaocong13 Thanks.
