### ISSUE TITLE
3D point cloud Projection

### ISSUE THREAD

**Issue by Hello-hubKing** [gaocong13/Projective-Spatial-Transformers#9]
Hi, I noticed that you mentioned voxel grid projection of 3d point cloud. Can you realize direct projection of 3d point cloud.

**Comment by gaocong13** [comment]
Hello, a short answer is yes. As long as it follows the projective geometry, the point cloud data can be projected onto 2D plane. However, the main novelty of this work is enabling differentiable projection for **volumetric 3D data**. especially with transmission imaging modalities. If it is point cloud data, then there is no need to perform ray casting and line integration.
